### ISSUE TITLE
timestamp column

### ISSUE THREAD

**Issue by syahirseth** [RikeshMMM/ESP32-CSI-Python-Parser#2]
Hi, can you tell me how did you get the timestamp column in the sample dataset

**Comment by RikeshMMM** [comment]
The tool used for collect CSI is [ESP32-CSI-Tool](https://github.com/StevenMHernandez/ESP32-CSI-Tool).
The [serial_append_time.py](https://github.com/StevenMHernandez/ESP32-CSI-Tool/blob/704ab3c12c518965f6084c30f0a055cd23b0b39f/python_utils/serial_append_time.py) python utility enables you to append the timestamp column.
